#!/bin/bash

if [[ -z $1 ]]; then
  echo "No input specified"
  exit
fi

file=$1
for i in input/$file*; do
  echo "Output of " $i
  bin/$file < input/$file 
  
  echo "Diff result: "
  bin/$file< input/$i | diff - output/${i/.in}.out
done
