#!/bin/bash

if [[ -z $1 ]]; then
	echo "No input specified"
  	exit
fi

file=$1
for in in input/$file*; do
	out=output/`basename ${in/.in}.out`
	sol=solution/`basename ${in/.in}.out`
	echo ${in^^}

	bin/$file < $in | tee $out
	if [[ -f $sol || $2 != 0 ]]; then
		echo ""
		echo "DIFF:"
		diff -y <(nl $out -s":  ")  <(nl $sol -s":  ")
		diff -q $sol $out
	fi
	echo _________________________________
	echo ""
done
